<?php
/**
 * AnalyticsDataDefaultMetricsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cervinodata API documentation
 *
 * <div style='margin: 2em 0;'><p>Before you get going with the Cervinodata API, set up Cervinodata (read the support page here: <a href='https://support.cervinodata.com/hc/en-nl/articles/360004363237' target='_blank'>How to set up the Cervinodata API</a>).</p> <h3>To use the Cervinodata API, you need all of the following:</h3> <p> <ol> <li>An active Cervinodata account, you can start a free trial <a href='https://app.cervinodata.com/register' target='_blank'>here</a></li> <li>At least one connection to a platform (check <a href='https://app.cervinodata.com/pages/data-sources/connections' target='_blank'>here</a>)</li> <li>At least one account switched ON (check <a href='https://app.cervinodata.com/pages/data-sources/accounts' target='_blank'>here</a>)</li> <li>At least one data refresh executed (check <a href='https://app.cervinodata.com/pages/data-destinations-api/data-collection' target='_blank'>here</a>)</li> <li>An active API token (check <a href='https://app.cervinodata.com/settings#/api' target='_blank'>here</a>)</li> </ol> </p> <p> If you wish to automate your Cervinodata API connection, check out the list of client API's at <a href='https://github.com/Cervinodata' target='_blank'>https://github.com/Cervinodata</a>. </p> </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cervinodata.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AnalyticsDataDefaultMetricsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AnalyticsDataDefaultMetricsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getAnalyticsReportPerCampaignPerDay
     *
     * Return analytics report per campaign per day by organisation.
     *
     */
    public function testGetAnalyticsReportPerCampaignPerDay()
    {
    }

    /**
     * Test case for getAnalyticsReportPerChannelGroupPerDay
     *
     * Return analytics report per channel group per day by organisation.
     *
     */
    public function testGetAnalyticsReportPerChannelGroupPerDay()
    {
    }

    /**
     * Test case for getAnalyticsReportPerDevicePerChannelGroupPerOrganisationPerViewPerDay
     *
     * Return analytics report per device per channel group per organisation per view per day.
     *
     */
    public function testGetAnalyticsReportPerDevicePerChannelGroupPerOrganisationPerViewPerDay()
    {
    }

    /**
     * Test case for getAnalyticsReportPerDevicePerDay
     *
     * Return analytics report per device per day by organisation.
     *
     */
    public function testGetAnalyticsReportPerDevicePerDay()
    {
    }

    /**
     * Test case for getAnalyticsReportPerSourceMediumPerDay
     *
     * Return analytics report per source medium per day by organisation.
     *
     */
    public function testGetAnalyticsReportPerSourceMediumPerDay()
    {
    }
}
